<#
.SYNOPSIS
    Build the QtTaskManager standalone executable with Nuitka (via pyside6-deploy).

.DESCRIPTION
    Steps:
      1. Sync dependencies (incl. the 'dev' group that provides Nuitka) with uv.
      2. Regenerate app.ico from the programmatic icon.
      3. Run pyside6-deploy using pysidedeploy.spec (standalone, no console).

    Output lands in .\dist\QtTaskManager.dist\ (the standalone folder; exe +
    bundled Qt/Python runtime, per exec_directory in pysidedeploy.spec).

.PARAMETER SkipIcon
    Skip regenerating app.ico.

.PARAMETER Clean
    Remove previous build artifacts (dist, build, *.build, *.dist, *.onefile-build) first.

.PARAMETER Installer
    After building the exe, run Inno Setup (iscc) on installer.iss to produce
    dist\QtTaskManager-Setup-<version>.exe. Requires Inno Setup 6 on PATH (or at
    its default install location).

.EXAMPLE
    .\build.ps1
    .\build.ps1 -Clean
    .\build.ps1 -Installer
#>
[CmdletBinding()]
param(
    [switch]$SkipIcon,
    [switch]$Clean,
    [switch]$Installer
)

$ErrorActionPreference = 'Stop'
Set-Location -Path $PSScriptRoot

function Write-Step($msg) { Write-Host "==> $msg" -ForegroundColor Cyan }

# Resolve uv
$uv = Get-Command uv -ErrorAction SilentlyContinue
if (-not $uv) {
    throw "uv not found on PATH. Install from https://docs.astral.sh/uv/ or build manually."
}

if ($Clean) {
    Write-Step "Cleaning build artifacts"
    $targets = @('dist', 'build') + (Get-ChildItem -Path . -Directory -Filter '*.build' -ErrorAction SilentlyContinue).FullName `
                                  + (Get-ChildItem -Path . -Directory -Filter '*.dist' -ErrorAction SilentlyContinue).FullName `
                                  + (Get-ChildItem -Path . -Directory -Filter '*.onefile-build' -ErrorAction SilentlyContinue).FullName
    foreach ($t in $targets) {
        if ($t -and (Test-Path $t)) {
            Write-Host "    removing $t"
            Remove-Item -Recurse -Force $t
        }
    }
}

Write-Step "Syncing dependencies (uv sync --dev)"
& uv sync --dev
if ($LASTEXITCODE -ne 0) { throw "uv sync failed (exit $LASTEXITCODE)" }

if (-not $SkipIcon) {
    Write-Step "Regenerating app.ico"
    & uv run python build_icon.py
    if ($LASTEXITCODE -ne 0) { throw "icon generation failed (exit $LASTEXITCODE)" }
}

Write-Step "Building executable (pyside6-deploy)"
# pyside6-deploy copies the onefile exe into exec_directory (dist) but does not
# create that directory — ensure it exists, notably after -Clean removed it.
$execDir = Join-Path $PSScriptRoot 'dist'
if (-not (Test-Path $execDir)) { New-Item -ItemType Directory -Path $execDir | Out-Null }

# Bake the version, source commit and build date into the app so the About
# dialog can report them — the compiled exe has no git available at runtime.
# Generated, untracked, and removed again after the build (see finally below).
Write-Step "Baking build info (version, commit, date)"
$biVersion = (Select-String -Path (Join-Path $PSScriptRoot 'pyproject.toml') -Pattern '^\s*version\s*=\s*"([^"]+)"').Matches[0].Groups[1].Value
if (-not $biVersion) { throw "Could not read version from pyproject.toml" }
$biCommit = (& git rev-parse --short HEAD).Trim()
if ($LASTEXITCODE -ne 0 -or -not $biCommit) { $biCommit = 'unknown' }
$biDate = (Get-Date -Format 'yyyy-MM-dd HH:mm:ss zzz')
$buildInfoPath = Join-Path $PSScriptRoot 'procman\_build_info.py'
@"
# Generated by build.ps1 — do not edit or commit.
VERSION = "$biVersion"
COMMIT = "$biCommit"
DATE = "$biDate"
"@ | Set-Content -Path $buildInfoPath -Encoding utf8

# pyside6-deploy rewrites pysidedeploy.spec in place, baking the absolute,
# machine-specific python_path into the tracked file. Snapshot the exact bytes
# and restore them afterwards so a local build never leaves user-specific data
# (usernames, absolute paths) to be accidentally committed.
$specPath = Join-Path $PSScriptRoot 'pysidedeploy.spec'
$specBytes = [System.IO.File]::ReadAllBytes($specPath)
try {
    & uv run pyside6-deploy --force -c pysidedeploy.spec
    if ($LASTEXITCODE -ne 0) { throw "pyside6-deploy failed (exit $LASTEXITCODE)" }
} finally {
    [System.IO.File]::WriteAllBytes($specPath, $specBytes)
    if (Test-Path $buildInfoPath) { Remove-Item -Force $buildInfoPath }
}

# Standalone mode emits a folder (dist\QtTaskManager.dist) holding the exe plus
# its Qt/Python runtime — launching from it skips the per-start onefile unpack.
$exe = Join-Path $PSScriptRoot 'dist\QtTaskManager.dist\QtTaskManager.exe'
if (Test-Path $exe) {
    Write-Step "Done: $exe"
} else {
    # pyside6-deploy can exit 0 even when the underlying Nuitka compile fails,
    # so verify the artifact actually exists rather than trusting the exit code.
    throw "Build finished but $exe was not produced — the Nuitka compile likely failed; check the log above."
}

if ($Installer) {
    Write-Step "Building installer (Inno Setup)"

    # Resolve iscc: PATH first, then the standard Inno Setup 6 install locations.
    $iscc = (Get-Command iscc -ErrorAction SilentlyContinue).Source
    if (-not $iscc) {
        $candidates = @(
            "${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe",
            "$env:ProgramFiles\Inno Setup 6\ISCC.exe",
            "$env:LocalAppData\Programs\Inno Setup 6\ISCC.exe"
        )
        $iscc = $candidates | Where-Object { Test-Path $_ } | Select-Object -First 1
    }
    if (-not $iscc) {
        throw "Inno Setup (iscc) not found. Install from https://jrsoftware.org/isdl.php (or 'winget install JRSoftware.InnoSetup')."
    }

    # Keep the installer version in sync with pyproject.toml.
    $version = (Select-String -Path (Join-Path $PSScriptRoot 'pyproject.toml') -Pattern '^\s*version\s*=\s*"([^"]+)"').Matches[0].Groups[1].Value
    if (-not $version) { throw "Could not read version from pyproject.toml" }

    & $iscc "/DAppVersion=$version" (Join-Path $PSScriptRoot 'installer.iss')
    if ($LASTEXITCODE -ne 0) { throw "iscc failed (exit $LASTEXITCODE)" }

    $setup = Join-Path $PSScriptRoot "dist\QtTaskManager-Setup-$version.exe"
    if (Test-Path $setup) {
        Write-Step "Done: $setup"
    } else {
        throw "iscc reported success but $setup was not produced — check the log above."
    }
}
